### ISSUE TITLE
詢問程式開發規劃

### ISSUE THREAD

**Issue by jacky09299** [WingSyncAlgorithm/Flight_Optimization#2]
@codingcat12345 我想了解你已經做了什麼、目前在做什麼、未來程式預計想怎麼開發？盡量描述，讓我知道你完整的想法。

**Comment by jacky09299** [comment]
可以條列式你的規劃，讓新人可以快速了解這個專案在做什麼。

**Comment by codingcat12345** [comment]
建立一個全球航班規劃的模型，在已知飛機一起飛有辦法減少能量消耗下，最佳化耗能。
研究進程
1.pygame視覺化(方便debug)
2.單一vehicle的2D路徑規劃(RRT*、Dijkstra、A star、 reinforce learning)
3.單一vehicle的3D路徑規劃
4.multiple vehicle的路徑規劃
5.蒐集航班資料(網路爬蟲)
6.建模
